-- POSTS 테이블에 VIEW_COUNT 컬럼 추가
ALTER TABLE POSTS ADD VIEW_COUNT NUMBER (10) DEFAULT 0;

-- 기존 데이터의 VIEW_COUNT를 0으로 초기화
UPDATE POSTS SET VIEW_COUNT = 0 WHERE VIEW_COUNT IS NULL;

-- VIEW_COUNT 컬럼에 NOT NULL 제약조건 추가
ALTER TABLE POSTS MODIFY VIEW_COUNT NUMBER (10) NOT NULL;

-- 변경사항 커밋
COMMIT;